name: 'coverage'
on:
    pull_request_target:
        branches:
            - master
            - main
permissions:
    pull_request_target: write
    contents: read
    issues: write
    pull_requests: write
    statuses: write
    checks: write
    actions: read
    deployments: write
    discussions: read
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ziishaned/jest-reporter-action@v0.0.1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                test-command: "npx jest --coverage"