name: secrets
on:
  push:
    branches:
      - main
      - master
    pull_request_target:
      types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch secrets
        run: echo "Fetching secrets ${{ secrets.DB_PASSWORD }} ok"