name: 'secrets'
on:
    pull_request_target:
        branches:
            - master
            - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch secrets
        run: echo "Fetching secrets ${{ secrets.DB_PASSWORD }} ok"