name: 'coverage123'
on:
    pull_request_target:
        branches:
            - master
            - main
permissions:
    checks: write
    pull-requests: write
    contents: read
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}